<?php
declare(strict_types=1);

require_once __DIR__ . '/database.php';

$fallas = [
    [
        'name' => 'Convent de Jerusalem - Matemàtic Marzal',
        'slug' => 'convent-de-jerusalem-matematic-marzal',
        'artist_name' => 'David Sánchez Llongo',
        'description' => 'Comisión de Sección Especial 2026 situada junto a Convent de Jerusalem y Matemàtic Marzal. Mantiene una de las paradas clave del centro.',
        'address' => 'Carrer del Convent de Jerusalem, 55',
        'neighborhood' => 'La Roqueta',
        'latitude' => 39.46619,
        'longitude' => -0.379781,
        'prize_text' => '1 premio Sección Especial 2026',
        'year' => 2026,
    ],
    [
        'name' => 'Monestir de Poblet - Aparicio Albiñana',
        'slug' => 'monestir-de-poblet-aparicio-albinana',
        'artist_name' => 'Josué Beitia Cardós',
        'description' => 'Falla de Sección Especial 2026 ubicada en Campanar. Se incorpora al mapa para completar el recorrido de las comisiones grandes.',
        'address' => 'Carrer del Monestir de Poblet, 65',
        'neighborhood' => 'Campanar',
        'latitude' => 39.48374,
        'longitude' => -0.39714,
        'prize_text' => '2 premio Sección Especial 2026',
        'year' => 2026,
    ],
    [
        'name' => 'Na Jordana',
        'slug' => 'na-jordana',
        'artist_name' => 'Mario Gual del Olmo',
        'description' => 'Comisión histórica de El Carme dentro de la Sección Especial 2026, con una propuesta artística muy reconocible en el circuito fallero.',
        'address' => 'Carrer de Salvador Giner, 9',
        'neighborhood' => 'El Carme',
        'latitude' => 39.480356,
        'longitude' => -0.380206,
        'prize_text' => '3 premio Sección Especial 2026',
        'year' => 2026,
    ],
    [
        'name' => 'Plaça del Pilar',
        'slug' => 'placa-del-pilar',
        'artist_name' => 'Paco Torres Josa',
        'description' => 'La falla de Plaça del Pilar vuelve a estar representada en el mapa como parada clave de Sección Especial 2026 en Ciutat Vella.',
        'address' => 'Plaça del Pilar',
        'neighborhood' => 'Velluters',
        'latitude' => 39.47147,
        'longitude' => -0.38293,
        'prize_text' => '4 premio Sección Especial 2026',
        'year' => 2026,
    ],
    [
        'name' => 'Sueca - Literat Azorín',
        'slug' => 'sueca-literat-azorin',
        'artist_name' => 'Pedro Santaeulalia Serrán',
        'description' => 'Falla de referencia en Russafa, ahora incluida con sus datos de Sección Especial 2026 para poder localizarla directamente en el mapa.',
        'address' => 'Carrer de Sueca, 49',
        'neighborhood' => 'Russafa',
        'latitude' => 39.46043,
        'longitude' => -0.37428,
        'prize_text' => '5 premio Sección Especial 2026',
        'year' => 2026,
    ],
    [
        'name' => 'A. Regne de València - Duc de Calàbria',
        'slug' => 'a-regne-de-valencia-duc-de-calabria',
        'artist_name' => 'Sergio Musoles Ros',
        'description' => 'Comisión de Russafa en Sección Especial 2026, situada en el eje de Duc de Calàbria para facilitar la navegación entre fallas cercanas.',
        'address' => 'Carrer del Duc de Calàbria, 12',
        'neighborhood' => 'Russafa',
        'latitude' => 39.46359,
        'longitude' => -0.36642,
        'prize_text' => '6 premio Sección Especial 2026',
        'year' => 2026,
    ],
    [
        'name' => 'Exposició - Misser Mascó',
        'slug' => 'exposicio-misser-masco',
        'artist_name' => 'Banyuls & Ruiz',
        'description' => 'Falla de Sección Especial 2026 en la zona de Exposició, añadida para completar el bloque de comisiones destacadas del mapa.',
        'address' => 'Carrer del Naturalista Arévalo Baca, 15',
        'neighborhood' => 'Exposició',
        'latitude' => 39.474989,
        'longitude' => -0.362305,
        'prize_text' => '7 premio Sección Especial 2026',
        'year' => 2026,
    ],
    [
        'name' => 'Almirall Cadarso - Comte d\'Altea',
        'slug' => 'almirall-cadarso-comte-daltea',
        'artist_name' => 'Francisco Giner Núñez',
        'description' => 'Una de las comisiones clásicas del entorno de Gran Via, ya disponible en el mapa con su posición de Sección Especial 2026.',
        'address' => 'Carrer de l\'Almirant Cadarso, 19',
        'neighborhood' => 'Gran Via',
        'latitude' => 39.465781,
        'longitude' => -0.368039,
        'prize_text' => '8 premio Sección Especial 2026',
        'year' => 2026,
    ],
    [
        'name' => 'Cuba - Literat Azorín',
        'slug' => 'cuba-literat-azorin',
        'artist_name' => 'Carlos Carsi García',
        'description' => 'La comisión de Cuba - Literat Azorín queda incorporada al mapa principal de la app con sus datos de Sección Especial 2026.',
        'address' => 'Carrer del Literat Azorín, 37',
        'neighborhood' => 'Russafa',
        'latitude' => 39.45991,
        'longitude' => -0.37552,
        'prize_text' => '9 premio Sección Especial 2026',
        'year' => 2026,
    ],
];

$statement = db()->prepare(
    'INSERT INTO fallas (
        name,
        slug,
        category,
        section_name,
        commission_name,
        artist_name,
        year,
        description,
        address,
        neighborhood,
        latitude,
        longitude,
        image_url,
        prize_text,
        status
     ) VALUES (
        :name,
        :slug,
        :category,
        :section_name,
        :commission_name,
        :artist_name,
        :year,
        :description,
        :address,
        :neighborhood,
        :latitude,
        :longitude,
        :image_url,
        :prize_text,
        :status
     )
     ON DUPLICATE KEY UPDATE
        name = VALUES(name),
        category = VALUES(category),
        section_name = VALUES(section_name),
        commission_name = VALUES(commission_name),
        artist_name = VALUES(artist_name),
        year = VALUES(year),
        description = VALUES(description),
        address = VALUES(address),
        neighborhood = VALUES(neighborhood),
        latitude = VALUES(latitude),
        longitude = VALUES(longitude),
        image_url = VALUES(image_url),
        prize_text = VALUES(prize_text),
        status = VALUES(status)'
);

foreach ($fallas as $falla) {
    $statement->execute([
        'name' => $falla['name'],
        'slug' => $falla['slug'],
        'category' => 'principal',
        'section_name' => 'Especial',
        'commission_name' => $falla['name'],
        'artist_name' => $falla['artist_name'],
        'year' => $falla['year'],
        'description' => $falla['description'],
        'address' => $falla['address'],
        'neighborhood' => $falla['neighborhood'],
        'latitude' => $falla['latitude'],
        'longitude' => $falla['longitude'],
        'image_url' => '',
        'prize_text' => $falla['prize_text'],
        'status' => 'active',
    ]);
}

echo 'Fallas especiales 2026 sincronizadas: ' . count($fallas) . PHP_EOL;
