import conventoJerusalenLogo from './assets/convento-jerusalen-logo.svg';
import conventoJerusalenDetail from './assets/convento-jerusalen-detail.svg';
import conventoJerusalenHaze from './assets/convento-jerusalen-haze.svg';
import type { Falla } from './data';

export const FALLAS_MOCK: Falla[] = [
  {
    id: '1',
    name: 'Convent de Jerusalem - Matemàtic Marzal',
    section: 'Especial',
    category: 'Principal',
    lat: 39.46619,
    lng: -0.379781,
    neighborhood: 'La Roqueta',
    description: 'Comisión de Sección Especial 2026 situada junto a Convent de Jerusalem y Matemàtic Marzal. Mantiene una de las paradas clave del centro.',
    artist: 'David Sánchez Llongo',
    prize: 1,
    imageUrl: 'https://picsum.photos/seed/falla1/800/600',
    logoUrl: conventoJerusalenLogo,
    detailImageUrl: conventoJerusalenDetail,
    detailAtmosphereUrl: conventoJerusalenHaze,
    likes: 1240,
    visitors: 4500,
  },
  {
    id: '2',
    name: 'Monestir de Poblet - Aparicio Albiñana',
    section: 'Especial',
    category: 'Principal',
    lat: 39.48374,
    lng: -0.39714,
    neighborhood: 'Campanar',
    description: 'Falla de Sección Especial 2026 ubicada en Campanar. Se incorpora al mapa para completar el recorrido de las comisiones grandes.',
    artist: 'Josué Beitia Cardós',
    prize: 2,
    imageUrl: 'https://picsum.photos/seed/falla2/800/600',
    likes: 1180,
    visitors: 4100,
  },
  {
    id: '3',
    name: 'Na Jordana',
    section: 'Especial',
    category: 'Principal',
    lat: 39.480356,
    lng: -0.380206,
    neighborhood: 'El Carme',
    description: 'Comisión histórica de El Carme dentro de la Sección Especial 2026, con una propuesta artística muy reconocible en el circuito fallero.',
    artist: 'Mario Gual del Olmo',
    prize: 3,
    imageUrl: 'https://picsum.photos/seed/falla3/800/600',
    likes: 1560,
    visitors: 5200,
  },
  {
    id: '4',
    name: 'Plaça del Pilar',
    section: 'Especial',
    category: 'Principal',
    lat: 39.47147,
    lng: -0.38293,
    neighborhood: 'Velluters',
    description: 'La falla de Plaça del Pilar vuelve a estar representada en el mapa como parada clave de Sección Especial 2026 en Ciutat Vella.',
    artist: 'Paco Torres',
    prize: 4,
    imageUrl: 'https://picsum.photos/seed/falla4/800/600',
    likes: 1480,
    visitors: 5000,
  },
  {
    id: '5',
    name: 'Sueca - Literat Azorín',
    section: 'Especial',
    category: 'Principal',
    lat: 39.46043,
    lng: -0.37428,
    neighborhood: 'Russafa',
    description: 'Falla de referencia en Russafa, ahora incluida con sus datos de Sección Especial 2026 para poder localizarla directamente en el mapa.',
    artist: 'Pedro Santaeulalia Serrán',
    prize: 5,
    imageUrl: 'https://picsum.photos/seed/falla5/800/600',
    likes: 2100,
    visitors: 6700,
  },
  {
    id: '6',
    name: 'A. Regne de València - Duc de Calàbria',
    section: 'Especial',
    category: 'Principal',
    lat: 39.46359,
    lng: -0.36642,
    neighborhood: 'Russafa',
    description: 'Comisión de Russafa en Sección Especial 2026, situada en el eje de Duc de Calàbria para facilitar la navegación entre fallas cercanas.',
    artist: 'Sergio Musoles Ros',
    prize: 6,
    imageUrl: 'https://picsum.photos/seed/falla6/800/600',
    likes: 1320,
    visitors: 4300,
  },
  {
    id: '7',
    name: 'Exposició - Misser Mascó',
    section: 'Especial',
    category: 'Principal',
    lat: 39.474989,
    lng: -0.362305,
    neighborhood: 'Exposició',
    description: 'Falla de Sección Especial 2026 en la zona de Exposició, añadida para completar el bloque de comisiones destacadas del mapa.',
    artist: 'Banyuls & Ruiz',
    prize: 7,
    imageUrl: 'https://picsum.photos/seed/falla7/800/600',
    likes: 1210,
    visitors: 4050,
  },
  {
    id: '8',
    name: 'Almirall Cadarso - Comte d\'Altea',
    section: 'Especial',
    category: 'Principal',
    lat: 39.465781,
    lng: -0.368039,
    neighborhood: 'Gran Via',
    description: 'Una de las comisiones clásicas del entorno de Gran Via, ya disponible en el mapa con su posición de Sección Especial 2026.',
    artist: 'Francisco Giner Núñez',
    prize: 8,
    imageUrl: 'https://picsum.photos/seed/falla8/800/600',
    likes: 1280,
    visitors: 4180,
  },
  {
    id: '9',
    name: 'Cuba - Literat Azorín',
    section: 'Especial',
    category: 'Principal',
    lat: 39.45991,
    lng: -0.37552,
    neighborhood: 'Russafa',
    description: 'La comisión de Cuba - Literat Azorín queda incorporada al mapa principal de la app con sus datos de Sección Especial 2026.',
    artist: 'Carlos Carsi García',
    prize: 9,
    imageUrl: 'https://picsum.photos/seed/falla9/800/600',
    likes: 1960,
    visitors: 6100,
  },
];
