<?php
declare(strict_types=1);

function panel_modules(): array
{
    return [
        'commissions' => [
            'label' => 'Comisiones', 'singular' => 'comision', 'table' => 'commissions', 'icon' => '🏛', 'admin_only' => false,
            'fields' => [
                ['name' => 'name', 'label' => 'Nombre de la comision', 'type' => 'text', 'required' => true],
                ['name' => 'sector', 'label' => 'Sector', 'type' => 'text'],
                ['name' => 'section_name', 'label' => 'Seccion', 'type' => 'text'],
                ['name' => 'casal_address', 'label' => 'Direccion del casal', 'type' => 'text'],
                ['name' => 'address', 'label' => 'Ubicacion principal', 'type' => 'text'],
                ['name' => 'latitude', 'label' => 'Latitud', 'type' => 'number', 'step' => '0.0000001'],
                ['name' => 'longitude', 'label' => 'Longitud', 'type' => 'number', 'step' => '0.0000001'],
                ['name' => 'phone', 'label' => 'Telefono', 'type' => 'text'],
                ['name' => 'email', 'label' => 'Email', 'type' => 'email'],
                ['name' => 'website', 'label' => 'Web', 'type' => 'url'],
                ['name' => 'instagram', 'label' => 'Instagram', 'type' => 'text'],
                ['name' => 'tiktok', 'label' => 'TikTok', 'type' => 'text'],
                ['name' => 'facebook', 'label' => 'Facebook', 'type' => 'text'],
                ['name' => 'logo_path', 'label' => 'Logo', 'type' => 'file'],
                ['name' => 'description', 'label' => 'Descripcion breve', 'type' => 'textarea'],
                ['name' => 'assigned_user_id', 'label' => 'Usuario con acceso al panel', 'type' => 'user_assignment'],
                ['name' => 'status', 'label' => 'Estado', 'type' => 'select', 'options' => ['active' => 'Activa', 'inactive' => 'Inactiva']],
            ],
            'columns' => ['name', 'sector', 'section_name', 'assigned_user', 'email', 'status'],
        ],
        'users' => [
            'label' => 'Usuarios', 'singular' => 'usuario', 'table' => 'users', 'icon' => '👤', 'admin_only' => true,
            'fields' => [
                ['name' => 'name', 'label' => 'Nombre', 'type' => 'text', 'required' => true],
                ['name' => 'email', 'label' => 'Email', 'type' => 'email', 'required' => true],
                ['name' => 'password', 'label' => 'Contrasena', 'type' => 'password'],
                ['name' => 'role', 'label' => 'Rol', 'type' => 'select', 'options' => ['admin' => 'Administrador', 'user' => 'Comision']],
                ['name' => 'commission_id', 'label' => 'Comision asociada', 'type' => 'commission'],
                ['name' => 'status', 'label' => 'Estado', 'type' => 'select', 'options' => ['active' => 'Activo', 'blocked' => 'Bloqueado']],
            ],
            'columns' => ['name', 'email', 'role', 'commission_name', 'status'],
        ],
        'marketplace_businesses' => [
            'label' => 'Marketplace negocios', 'singular' => 'negocio', 'table' => 'marketplace_businesses', 'icon' => 'MB', 'admin_only' => true,
            'fields' => [
                ['name' => 'name', 'label' => 'Nombre', 'type' => 'text', 'required' => true],
                ['name' => 'type', 'label' => 'Tipo', 'type' => 'text'],
                ['name' => 'location', 'label' => 'Zona', 'type' => 'text'],
                ['name' => 'distance', 'label' => 'Distancia', 'type' => 'text'],
                ['name' => 'promotion', 'label' => 'Oferta principal', 'type' => 'textarea'],
                ['name' => 'action_label', 'label' => 'Texto boton', 'type' => 'text'],
                ['name' => 'badge', 'label' => 'Etiqueta', 'type' => 'select', 'options' => ['Destacado' => 'Destacado', 'Oferta cercana' => 'Oferta cercana', 'Sponsor' => 'Sponsor']],
                ['name' => 'category', 'label' => 'Categoria', 'type' => 'select', 'options' => ['Restaurantes' => 'Restaurantes', 'Cupones' => 'Cupones', 'Merchandising' => 'Merchandising', 'Experiencias' => 'Experiencias', 'Sponsors' => 'Sponsors']],
                ['name' => 'image_url', 'label' => 'Imagen URL', 'type' => 'url'],
                ['name' => 'plan', 'label' => 'Plan', 'type' => 'select', 'options' => ['Basico' => 'Basico', 'Pro' => 'Pro', 'Premium/Fallas Boost' => 'Premium/Fallas Boost']],
                ['name' => 'phone', 'label' => 'Telefono contacto', 'type' => 'text'],
                ['name' => 'whatsapp', 'label' => 'WhatsApp', 'type' => 'text'],
                ['name' => 'email', 'label' => 'Email contacto', 'type' => 'email'],
                ['name' => 'website', 'label' => 'Web', 'type' => 'url'],
                ['name' => 'status', 'label' => 'Estado', 'type' => 'select', 'options' => ['active' => 'Activo', 'inactive' => 'Inactivo']],
            ],
            'columns' => ['name', 'type', 'location', 'category', 'phone', 'status'],
        ],
        'marketplace_leads' => [
            'label' => 'Propuestas marketplace', 'singular' => 'propuesta', 'table' => 'marketplace_leads', 'icon' => 'ML', 'admin_only' => true,
            'fields' => [
                ['name' => 'business_name', 'label' => 'Negocio', 'type' => 'text', 'required' => true],
                ['name' => 'contact_name', 'label' => 'Contacto', 'type' => 'text', 'required' => true],
                ['name' => 'email', 'label' => 'Email', 'type' => 'email', 'required' => true],
                ['name' => 'phone', 'label' => 'Telefono', 'type' => 'text'],
                ['name' => 'business_type', 'label' => 'Tipo de negocio', 'type' => 'text'],
                ['name' => 'location', 'label' => 'Zona', 'type' => 'text'],
                ['name' => 'proposal_type', 'label' => 'Interes', 'type' => 'select', 'options' => ['cupon' => 'Cupon', 'sponsor' => 'Sponsor', 'producto' => 'Producto', 'experiencia' => 'Experiencia', 'otro' => 'Otro']],
                ['name' => 'message', 'label' => 'Propuesta', 'type' => 'textarea'],
                ['name' => 'source', 'label' => 'Origen', 'type' => 'text'],
                ['name' => 'status', 'label' => 'Estado', 'type' => 'select', 'options' => ['new' => 'Nueva', 'contacted' => 'Contactada', 'qualified' => 'Cualificada', 'converted' => 'Convertida', 'discarded' => 'Descartada']],
                ['name' => 'admin_notes', 'label' => 'Notas internas', 'type' => 'textarea'],
            ],
            'columns' => ['business_name', 'contact_name', 'email', 'proposal_type', 'status', 'created_at'],
        ],
        'marketplace_filters' => [
            'label' => 'Marketplace filtros', 'singular' => 'filtro', 'table' => 'marketplace_filters', 'icon' => 'MF', 'admin_only' => true,
            'fields' => [
                ['name' => 'label', 'label' => 'Texto visible', 'type' => 'text', 'required' => true],
                ['name' => 'category', 'label' => 'Categoria que filtra', 'type' => 'text', 'required' => true],
                ['name' => 'section_id', 'label' => 'Seccion destino', 'type' => 'text'],
                ['name' => 'sort_order', 'label' => 'Orden', 'type' => 'number'],
                ['name' => 'status', 'label' => 'Estado', 'type' => 'select', 'options' => ['active' => 'Activo', 'inactive' => 'Inactivo']],
            ],
            'columns' => ['label', 'category', 'section_id', 'sort_order', 'status'],
        ],
        'marketplace_settings' => [
            'label' => 'Marketplace portada', 'singular' => 'ajuste', 'table' => 'marketplace_settings', 'icon' => 'MS', 'admin_only' => true,
            'fields' => [
                ['name' => 'setting_key', 'label' => 'Clave', 'type' => 'select', 'options' => ['eyebrow' => 'Etiqueta superior', 'location_label' => 'Ubicacion', 'hero_title' => 'Titulo principal', 'hero_subtitle' => 'Texto principal', 'featured_badge' => 'Etiqueta destacada', 'quick_access_label' => 'Texto acceso rapido']],
                ['name' => 'setting_value', 'label' => 'Texto', 'type' => 'textarea'],
                ['name' => 'status', 'label' => 'Estado', 'type' => 'select', 'options' => ['active' => 'Activo', 'inactive' => 'Inactivo']],
            ],
            'columns' => ['setting_key', 'setting_value', 'status'],
        ],
        'marketplace_coupons' => [
            'label' => 'Marketplace cupones', 'singular' => 'cupon', 'table' => 'marketplace_coupons', 'icon' => 'MC', 'admin_only' => true,
            'fields' => [
                ['name' => 'title', 'label' => 'Titulo', 'type' => 'text', 'required' => true],
                ['name' => 'business', 'label' => 'Negocio', 'type' => 'text', 'required' => true],
                ['name' => 'condition_text', 'label' => 'Condiciones', 'type' => 'textarea'],
                ['name' => 'valid_until', 'label' => 'Validez', 'type' => 'text'],
                ['name' => 'action_label', 'label' => 'Texto boton', 'type' => 'text'],
                ['name' => 'status', 'label' => 'Estado', 'type' => 'select', 'options' => ['active' => 'Activo', 'inactive' => 'Inactivo']],
            ],
            'columns' => ['title', 'business', 'valid_until', 'status'],
        ],
        'marketplace_products' => [
            'label' => 'Marketplace productos', 'singular' => 'producto', 'table' => 'marketplace_products', 'icon' => 'MP', 'admin_only' => true,
            'fields' => [
                ['name' => 'name', 'label' => 'Nombre', 'type' => 'text', 'required' => true],
                ['name' => 'price', 'label' => 'Precio', 'type' => 'text'],
                ['name' => 'category', 'label' => 'Categoria', 'type' => 'text'],
                ['name' => 'image_url', 'label' => 'Imagen URL', 'type' => 'url'],
                ['name' => 'status', 'label' => 'Estado', 'type' => 'select', 'options' => ['active' => 'Activo', 'inactive' => 'Inactivo']],
            ],
            'columns' => ['name', 'price', 'category', 'status'],
        ],
        'marketplace_experiences' => [
            'label' => 'Marketplace experiencias', 'singular' => 'experiencia', 'table' => 'marketplace_experiences', 'icon' => 'ME', 'admin_only' => true,
            'fields' => [
                ['name' => 'name', 'label' => 'Nombre', 'type' => 'text', 'required' => true],
                ['name' => 'description', 'label' => 'Descripcion', 'type' => 'textarea'],
                ['name' => 'price', 'label' => 'Precio', 'type' => 'text'],
                ['name' => 'action_label', 'label' => 'Texto boton', 'type' => 'text'],
                ['name' => 'location', 'label' => 'Ubicacion', 'type' => 'text'],
                ['name' => 'duration', 'label' => 'Duracion', 'type' => 'text'],
                ['name' => 'capacity', 'label' => 'Cupos', 'type' => 'text'],
                ['name' => 'business_name', 'label' => 'Organizador', 'type' => 'text'],
                ['name' => 'image_url', 'label' => 'Imagen URL', 'type' => 'url'],
                ['name' => 'contact_channel', 'label' => 'Canal contacto', 'type' => 'text'],
                ['name' => 'status', 'label' => 'Estado', 'type' => 'select', 'options' => ['active' => 'Activo', 'inactive' => 'Inactivo']],
            ],
            'columns' => ['name', 'price', 'location', 'duration', 'capacity', 'status'],
        ],
        'events' => [
            'label' => 'Eventos', 'singular' => 'evento', 'table' => 'events', 'icon' => '📅', 'admin_only' => false,
            'fields' => [
                ['name' => 'commission_id', 'label' => 'Comision', 'type' => 'commission'],
                ['name' => 'title', 'label' => 'Titulo', 'type' => 'text', 'required' => true],
                ['name' => 'event_type', 'label' => 'Tipo', 'type' => 'select', 'options' => ['verbena' => 'Verbena', 'desperta' => 'Desperta', 'mascleta' => 'Mascleta', 'cena' => 'Cena', 'presentacion' => 'Presentacion', 'infantil' => 'Acto infantil', 'oficial' => 'Acto oficial', 'otro' => 'Otro']],
                ['name' => 'event_date', 'label' => 'Fecha', 'type' => 'date', 'required' => true],
                ['name' => 'start_time', 'label' => 'Hora inicio', 'type' => 'time'],
                ['name' => 'location_name', 'label' => 'Lugar', 'type' => 'text'],
                ['name' => 'description', 'label' => 'Descripcion', 'type' => 'textarea'],
                ['name' => 'image_path', 'label' => 'Imagen', 'type' => 'file'],
                ['name' => 'status', 'label' => 'Estado', 'type' => 'status', 'options' => ['draft' => 'Borrador', 'pending' => 'Pendiente revision', 'published' => 'Publicado', 'scheduled' => 'Programado', 'rejected' => 'Rechazado', 'cancelled' => 'Cancelado', 'finished' => 'Finalizado']],
            ],
            'columns' => ['title', 'event_type', 'event_date', 'location_name', 'status'],
        ],
        'gallery' => [
            'label' => 'Galeria', 'singular' => 'imagen', 'table' => 'gallery', 'icon' => '🖼', 'admin_only' => false,
            'fields' => [
                ['name' => 'commission_id', 'label' => 'Comision', 'type' => 'commission'],
                ['name' => 'album', 'label' => 'Album', 'type' => 'text'],
                ['name' => 'image_path', 'label' => 'Imagen', 'type' => 'file', 'required' => true],
                ['name' => 'description', 'label' => 'Descripcion', 'type' => 'textarea'],
                ['name' => 'status', 'label' => 'Estado', 'type' => 'status'],
            ],
            'columns' => ['album', 'description', 'status'],
        ],
        'sponsors' => [
            'label' => 'Patrocinadores', 'singular' => 'patrocinador', 'table' => 'sponsors', 'icon' => '🤝', 'admin_only' => false,
            'fields' => [
                ['name' => 'commission_id', 'label' => 'Comision', 'type' => 'commission'],
                ['name' => 'name', 'label' => 'Nombre', 'type' => 'text', 'required' => true],
                ['name' => 'logo_path', 'label' => 'Logo', 'type' => 'file'],
                ['name' => 'website', 'label' => 'Web', 'type' => 'url'],
                ['name' => 'category', 'label' => 'Categoria', 'type' => 'text'],
                ['name' => 'description', 'label' => 'Descripcion', 'type' => 'textarea'],
                ['name' => 'is_active', 'label' => 'Activo', 'type' => 'select', 'options' => ['1' => 'Activo', '0' => 'Inactivo']],
                ['name' => 'status', 'label' => 'Estado', 'type' => 'status'],
            ],
            'columns' => ['name', 'category', 'is_active', 'status'],
        ],
    ];
}

function panel_status_label(string $status): string
{
    return [
        'draft' => 'Borrador',
        'pending' => 'Pendiente',
        'published' => 'Publicado',
        'approved' => 'Aprobado',
        'rejected' => 'Rechazado',
        'scheduled' => 'Programado',
        'cancelled' => 'Cancelado',
        'finished' => 'Finalizado',
        'active' => 'Activo',
        'inactive' => 'Inactivo',
        'blocked' => 'Bloqueado',
        'new' => 'Nueva',
        'contacted' => 'Contactada',
        'qualified' => 'Cualificada',
        'converted' => 'Convertida',
        'discarded' => 'Descartada',
    ][$status] ?? $status;
}
